name             "exhibitor"
maintainer       "Simple Finance Technology Corp."
maintainer_email "ops@simple.com"
license          "Apache v2.0"
description      "Installs/Configures Netflix Exhibitor"
version          "0.1.0"

depends          "build-essential"
depends          "java"
depends          "runit"
depends          "zookeeper", ">= 2.0.0"
