name             'exhibitor'
maintainer       'Simple Finance Technology Corp.'
maintainer_email 'ops@simple.com'
license          'Apache v2.0'
description      'Installs Netflix Exhibitor'
version          '0.9.0'

depends          'build-essential', '~> 2.2'
depends          'java', '~> 1.35'
depends          'runit', '~> 1.7'
depends          'zookeeper', '~> 4.0'
