name 'exhibitor'
maintainer 'Simple Finance Technology Corp.'
maintainer_email 'ops@simple.com'
license 'Apache v2.0'
description 'Installs Netflix Exhibitor'
long_description 'Exhibitor'
version '0.4.0'

depends 'build-essential'
depends 'java'
depends 'runit'
depends 'zookeeper', '>= 2.0.0'
